# Build
FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY frete-contract/pom.xml frete-contract/
COPY frete-service/pom.xml frete-service/
COPY checkout-service/pom.xml checkout-service/
COPY pedidos-service/pom.xml pedidos-service/
COPY api-gateway/pom.xml api-gateway/
COPY frete-contract/src frete-contract/src
COPY pedidos-service/src pedidos-service/src
RUN mvn -q -pl frete-contract,pedidos-service -am package -DskipTests

# Runtime
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/pedidos-service/target/pedidos-service.jar app.jar
EXPOSE 50052
ENTRYPOINT ["java", "-jar", "app.jar"]
