spring.application.name=api-gateway
server.port=8080

gateway.frete.alvo=${FRETE_ALVO:localhost:50051}
gateway.pedidos.alvo=${PEDIDOS_ALVO:localhost:50052}

gateway.auth.usuario=${AUTH_USUARIO:admin}
gateway.auth.senha=${AUTH_SENHA:admin123}
gateway.jwt.segredo=${JWT_SEGREDO:troque-este-segredo-por-um-bem-grande-e-secreto-0123456789}
gateway.jwt.expiracao-min=${JWT_EXPIRACAO_MIN:60}
